language: python
python:
  - "3.6"
  
#before_install:
#  - sudo apt-get install -y graphviz
  
  # command to install dependencies
install:
  $ pip install -U -r requirements.txt
  $ pip install .
  $ pytest -vvv tests
  
# command to run tests
script:
  - pytest
