language: python
python:
  - "3.6"
  
  # command to install dependencies
install:
  - install graphviz
  - pip install -U -r requirements.txt
  - pip install .
  - pytest -vvv tests
  
# command to run tests
script:
  - pytest
